G_CROSS_NAME=riscv64-linux-musl

VAR_CROSS_COMPILE=${G_CROSS_NAME}-

CC=${VAR_CROSS_COMPILE}gcc
CXX=${VAR_CROSS_COMPILE}g++

LD=${VAR_CROSS_COMPILE}ld
AS=${VAR_CROSS_COMPILE}as

AR=${VAR_CROSS_COMPILE}ar
NM=${VAR_CROSS_COMPILE}nm
STRIP=${VAR_CROSS_COMPILE}strip
OBJCOPY=${VAR_CROSS_COMPILE}objcopy
OBJDUMP=${VAR_CROSS_COMPILE}objdump

export CC CXX LD AS AR NM STRIP OBJCOPY OBJDUMP

CROSS_FLAG="ARCH=riscv CROSS_COMPILE=${VAR_CROSS_COMPILE}"
MAKE="make ${CROSS_FLAG}"

${MAKE}
